# <BASE_PRICE> <PRICE_PER_DAY> <MOUNT_PRICE> <DEBT> <TOTAL_PRICE> <DAYS> <MOUNT_NAME> <MOUNT_TYPE> <MOUNT_PAMPERED>

  auto-save: 60 #interval for auto-saving in minutes.
  check-update: true #automatically checks for updates. Set to false to disable.
   
  mount-cost: #setting of -1 disables sale. 0 enables free give-away.
    pig: 50
    horse: -1
    donkey: -1
    mule: -1
  text:
    greet: "&eHello there! May I help you with anything?"
    nil: "&cI'm afraid I don't have anything of yours."
    funds: "&cYou can't afford it!"
    invalid: "&cYou look lost. You have nothing I can look after!"
    full: "&cI'm afraid I'm all out of room!"
    give: "&eGreat! Here's <MOUNT_NAME>!"
    broke: "&eYou've come up short. Take the <MOUNT_TYPE>. I'll collect next time."
    debt: "&eI still need you to pay up from last time. It was &a<DEBT>&e."
    paid: "&eThanks! Now what can I do for you?"
    stow: "&eDon't you worry! I'll take fine care of <MOUNT_NAME>!"
    pay: "&2[&fMoney&2] You have sent &f<AMOUNT> &2to &f<NPC_NAME>&2."
  noble:
    stow: "&eExcellent! I'll care for <MOUNT_NAME> as if it were my own."
    free: "&eYour grace! Please take my finest <MOUNT_TYPE>. It is an honor!"
    give: "&eHere is <MOUNT_NAME>, your grace. <MOUNT_PAMPERED>"
  
  stable:
    max-mounts: 27 #value of 0 = unlimited. Must be divisible by 9.
    price-init: 4
    price-per-day: 2
    cooldown: 4 #noble free mount cooldown (in hours).
    pampered: "Bathed, brushed, and pampered!"
    
    free-mount: Pig #type of free mount (Pig, Horse, Donkey, Mule)
    random-names: "Petunia, Buddy, Stella, Herbert, Emett, Jebediah, Sully, Professor, Farley, Mickey"
    gui:
      name: &f # color of names in stable gui
      bill: &c # color of bill amount in stable gui
      text: &a # color of 'paid' message in stable gui
      
  wharf:
    max-mounts: 64
    price-init: 2
    location-log: true # place vehicle where it was taken from? else throw item down
    pampered: "I even scrubbed down the hull!"
    
  station:
    max-mounts: 64
    price-init: 2
    location-log: true
    pampered: "Washed and waxed to a brand new shine!"